In [1]:
import json

# Open and read the JSON file
with open('/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/training.json', 'r') as file:
    train_data = json.load(file)
with open('/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/test.json', 'r') as file:
    test_data = json.load(file)

In [2]:
for i in train_data:
    if train_data[i]['labels_task4'].count('YES') > train_data[i]['labels_task4'].count('NO'):
        train_data[i]['labels_task4'] = 1
    else:
        train_data[i]['labels_task4'] = 0

print(train_data['110002']['labels_task4'])

1


In [3]:
import pandas as pd
import numpy as np

train_df = pd.DataFrame(train_data)
test_df = pd.DataFrame(test_data)

In [4]:
train_df = train_df.transpose()
test_df = test_df.transpose()

In [5]:
train_df.head()

id_EXIST lang                                               text  \
110002   110002   es     CUANDO UNA MUJER VA A LUCHAR POR SUS DERECHOS    
110006   110006   es  Princesa, hoy es tu día, no laves ningún plato...   
110007   110007   es  SpartanlanceWTF @SpartanLance 3 min Sorry, no ...   
110009   110009   es  Barto @Bart045603771 El 8m de mañana: 3 M.C. (...   
110013   110013   es  Dime feliz día cuando ya no maten mas mujeres ...   

               meme         path_memes number_annotators  \
110002  110002.jpeg  memes/110002.jpeg                 6   
110006  110006.jpeg  memes/110006.jpeg                 6   
110007  110007.jpeg  memes/110007.jpeg                 6   
110009  110009.jpeg  memes/110009.jpeg                 6   
110013  110013.jpeg  memes/110013.jpeg                 6   

                                               annotators   gender_annotators  \
110002  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110006  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110007  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110009  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110013  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   

                                age_annotators  \
110002  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110006  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110007  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110009  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110013  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   

                                   ethnicities_annotators  \
110002  [Hispano or Latino, Hispano or Latino, Hispano...   
110006  [Hispano or Latino, Hispano or Latino, Hispano...   
110007  [Hispano or Latino, Hispano or Latino, Hispano...   
110009  [Hispano or Latino, Hispano or Latino, Hispano...   
110013  [Hispano or Latino, Hispano or Latino, Hispano...   

                                  study_levels_annotators  \
110002  [High school degree or equivalent, Master’s de...   
110006  [High school degree or equivalent, Master’s de...   
110007  [High school degree or equivalent, Master’s de...   
110009  [High school degree or equivalent, Master’s de...   
110013  [High school degree or equivalent, Master’s de...   

                                     countries_annotators labels_task4  \
110002  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]            1   
110006  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]            1   
110007  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]            1   
110009  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]            1   
110013  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]            1   

                                             labels_task5  \
110002  [DIRECT, DIRECT, DIRECT, DIRECT, DIRECT, JUDGE...   
110006   [DIRECT, DIRECT, DIRECT, DIRECT, DIRECT, DIRECT]   
110007   [DIRECT, DIRECT, DIRECT, DIRECT, DIRECT, DIRECT]   
110009        [DIRECT, DIRECT, DIRECT, -, DIRECT, DIRECT]   
110013        [-, JUDGEMENTAL, DIRECT, -, DIRECT, DIRECT]   

                                             labels_task6          split  
110002  [[IDEOLOGICAL-INEQUALITY, STEREOTYPING-DOMINAN...  TRAIN-MEME_ES  
110006  [[IDEOLOGICAL-INEQUALITY, STEREOTYPING-DOMINAN...  TRAIN-MEME_ES  
110007  [[IDEOLOGICAL-INEQUALITY, STEREOTYPING-DOMINAN...  TRAIN-MEME_ES  
110009  [[IDEOLOGICAL-INEQUALITY, MISOGYNY-NON-SEXUAL-...  TRAIN-MEME_ES  
110013  [[-], [MISOGYNY-NON-SEXUAL-VIOLENCE], [IDEOLOG...  TRAIN-MEME_ES

In [6]:
test_df.head()

id_EXIST lang                                               text  \
110001   110001   es  2+2=5 MITO Albert Einstein tenía bajo rendimie...   
110003   110003   es  ІЯ ЕГЕЯ Е MOA ¿El Partido Republicano busca pe...   
110005   110005   es  Ya verás como este 8 de marzo hay uno que te s...   
110008   110008   es  Ay si ay si el dia de la Mujer.. =) V www Y to...   
110012   110012   es  A LOS QUE NO ME SALUDAN POR EL DIA DE LA MUJER...   

               meme         path_memes number_annotators  \
110001  110001.jpeg  memes/110001.jpeg                 6   
110003  110003.jpeg  memes/110003.jpeg                 6   
110005  110005.jpeg  memes/110005.jpeg                 6   
110008  110008.jpeg  memes/110008.jpeg                 6   
110012  110012.jpeg  memes/110012.jpeg                 6   

                                               annotators   gender_annotators  \
110001  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110003  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110005  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110008  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   
110012  [Annotator_1, Annotator_2, Annotator_3, Annota...  [F, F, F, M, M, M]   

                                age_annotators  \
110001  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110003  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110005  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110008  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   
110012  [18-22, 23-45, 46+, 46+, 18-22, 23-45]   

                                   ethnicities_annotators  \
110001  [Hispano or Latino, Hispano or Latino, Hispano...   
110003  [Hispano or Latino, Hispano or Latino, Hispano...   
110005  [Hispano or Latino, Hispano or Latino, Hispano...   
110008  [Hispano or Latino, Hispano or Latino, Hispano...   
110012  [Hispano or Latino, Hispano or Latino, Hispano...   

                                  study_levels_annotators  \
110001  [High school degree or equivalent, Master’s de...   
110003  [High school degree or equivalent, Master’s de...   
110005  [High school degree or equivalent, Master’s de...   
110008  [High school degree or equivalent, Master’s de...   
110012  [High school degree or equivalent, Master’s de...   

                                     countries_annotators        split  
110001  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]  DEV-MEME_ES  
110003  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]  DEV-MEME_ES  
110005  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]  DEV-MEME_ES  
110008  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]  DEV-MEME_ES  
110012  [Mexico, Spain, Argentina, Spain, Mexico, Mexico]  DEV-MEME_ES

In [7]:
train_df.shape, test_df.shape

((2723, 16), (697, 13))

In [8]:
import re
import string

def remove_username(text):
    user = re.compile(r"@[^\s]+")
    return user.sub(r"", text)

def remove_URL(text):
    url = re.compile(r"https?://\S+|www\.\S+")
    return url.sub(r"", text)

def remove_punct(text):
    translator = str.maketrans("", "", string.punctuation)
    return text.translate(translator)

def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           u"\U0001F923"
                           u"\U0001F972"
                           u"\U0001F973"
                           u"\U0001F9D0"
                           u"\U0001F9E1"
                           u"\U0001F49B"
                           u"\U0001F924"
                           u"\U0001F921"
                           u"\U0001F49C"
                           u"\U0001F914"
                           u"\U0001F97A"
                           u"\U0001F970"
                           u"\U0001F974"
                           u"\U0001F922"
                           u"\U0001F91D"
                           u"\U0001F92A"
                           u"\U0001F92F"
                           u"\U0001F98A"
                           u"\U0001F981"
                           u"\U0001F926"
                           u"\U0001F937"
                           u"\U0001F92B"
                           u"\U0001F92E"
                           u"\U0001F90F"
                           u"\U0001F91F"
                           u"\U0001F92D"
                           u"\U0001F971"
                           u"\U0001F911"
                           u"\U0001F917"
                           u"\U0001F918"
                           u"\U0001F929"
                           u"\U0001F975"
                           u"\U0001F915"
                           u"\U0001F920"
                           u"\U0001F932"
                           u"\U0001F91E"
                           u"\U0001F928"
                           u"\U0001F92C"
                           u"\U0001F976"
                           u"\U0001F9E0"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [9]:
train_df['text'] = train_df.text.map(remove_username)
train_df['text'] = train_df.text.map(remove_URL)
train_df['text'] = train_df.text.map(remove_punct)
train_df['text'] = train_df.text.map(remove_emoji)
test_df['text'] = test_df.text.map(remove_username)
test_df['text'] = test_df.text.map(remove_URL)
test_df['text'] = test_df.text.map(remove_punct)
test_df['text'] = test_df.text.map(remove_emoji)

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = set(stopwords.words(fileids=('english', 'spanish')))
def remove_stopwords(text):
    filtered_words = [word.lower() for word in text.split() if word.lower() not in stop]
    return " ".join(filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/naranja/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
train_df['text'] = train_df.text.map(remove_stopwords)
test_df['text'] = test_df.text.map(remove_stopwords)

In [12]:
csv_file_train = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/training.csv'
csv_file_test = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/test.csv'
train_df.to_csv(csv_file_train, index=False)
test_df.to_csv(csv_file_test, index=False)

In [13]:
# Let's visualize some random training examples
import random

random_index = random.randint(0, len(train_df)-5) # create random indexes not higher than the total number of samples
for row in train_df[["id_EXIST", "text", "labels_task4"]][random_index:random_index+5].itertuples():
  _, id_EXIST, text, target = row
  print(f"ID:\n{id_EXIST}\n")
  print(f"Target: {target}", "(misogynous memes)" if target > 0 else "(not misogynous memes)")
  print(f"Text:\n{text}\n")
  print("---\n")

ID:
110062

Target: 1 (misogynous memes)
Text:
imgflipcom undiasinnosotras instituciones despedir acosadores

---

ID:
110067

Target: 0 (not misogynous memes)
Text:
macho

---

ID:
110070

Target: 1 (misogynous memes)
Text:
mujer tranquila vuelve cocina memegeneratores

---

ID:
110071

Target: 1 (misogynous memes)
Text:
44 calla hand cocina memegeneratores

---

ID:
110072

Target: 1 (misogynous memes)
Text:
buen intento ahora regresa cocina memes 24 app

---



In [14]:
from sklearn.model_selection import train_test_split

# Use train_test_split to split training data into training and validation sets
train_text, val_text, train_labels, val_labels, train_id, val_id = train_test_split(train_df["text"].to_numpy(),
                                                                  train_df["labels_task4"].to_numpy(),
                                                                  train_df["id_EXIST"].to_numpy(),
                                                                  test_size=0.1, # dedicate 10% of samples to validation set
                                                                  random_state=42) # random state for reproducibility

In [15]:
blip_caption = pd.read_csv('/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_captions_training.csv')
blip_caption_text = blip_caption["blip_caption"].to_numpy()
blip_caption_labels = blip_caption["meme_id"].to_numpy()

In [16]:
len(train_text), len(train_labels), len(val_text), len(val_labels)

(2450, 2450, 273, 273)

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization # after TensorFlow 2.6

# Use the default TextVectorization variables
text_vectorizer = TextVectorization(max_tokens=None, # how many words in the vocabulary (all of the different words in your text)
                                    standardize="lower_and_strip_punctuation", # how to process text
                                    split="whitespace", # how to split tokens
                                    ngrams=None, # create groups of n-words?
                                    output_mode="int", # how to map tokens to numbers
                                    output_sequence_length=None) # how long should the output sequence of tokens be?
                                    # pad_to_max_tokens=True) # Not valid if using max_tokens=None

2025-03-14 11:18:43.889577: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [18]:
# Find average number of tokens (words) in training Tweets
round(sum([len(i.split()) for i in train_text])/len(train_text))

12

In [19]:
# Setup text vectorization with custom variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 12 # max length our sequences will be (e.g. how many words from a Tweet does our model see?)

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [20]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(train_text)

In [21]:
# Create sample sentence and tokenize it
sample_sentence = "Mucho gusto, mi nombre es!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 12), dtype=int64, numpy=
array([[   1,  844,    1, 6822,    1,    0,    0,    0,    0,    0,    0,
           0]])>

In [22]:
# Choose a random sentence from the training dataset and tokenize it
random_sentence = random.choice(train_text)
print(f"Original text:\n{random_sentence}\
      \n\nVectorized version:")
text_vectorizer([random_sentence])

Original text:
1040 pm 1109 pm much power image snapping fingers kills half universe imagine slapping ass would      

Vectorized version:


<tf.Tensor: shape=(1, 12), dtype=int64, numpy=
array([[   1,   72, 3846,   72,  150,  657, 1863, 5189, 3235, 7740,  453,
        1172]])>

In [23]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary()
top_5_words = words_in_vocab[:5] # most common tokens (notice the [UNK] token for "unknown" words)
bottom_5_words = words_in_vocab[-5:] # least common tokens
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"Top 5 most common words: {top_5_words}") 
print(f"Bottom 5 least common words: {bottom_5_words}")


Number of words in vocab: 10000
Top 5 most common words: ['', '[UNK]', 'women', 'men', 'mujer']
Bottom 5 least common words: ['conclusiones', 'conclusion', 'conchi', 'concha', 'conceptos']


In [24]:
tf.random.set_seed(42)
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128, # set size of embedding vector
                             embeddings_initializer="uniform", # default, intialize randomly
                             input_length=max_length, # how long is each input
                             name="embedding_1")
embedding

/Users/naranja/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<Embedding name=embedding_1, built=False>

In [25]:
# Get a random sentence from training set
result = random.choice(train_text)
print(f"Original text:\n{result}\
      \n\nEmbedded version:")

# Embed the random sentence (turn it into numerical representation)
sample_embed = embedding(text_vectorizer([result]))
sample_embed

Original text:
¿qué gustan preliminares shue muno imgflipcom ¡yo dicho ¡sólo digo gusta utilices palabra víctima coitocentrismo gusta contenido ¡no concepto ¿preliminar ¿cómo quieres llame comas polla follar lees blog sexo entienda      

Embedded version:


<tf.Tensor: shape=(1, 12, 128), dtype=float32, numpy=
array([[[-0.01251137, -0.01228081, -0.0205703 , ..., -0.03401028,
         -0.03437271, -0.0176703 ],
        [ 0.02259408, -0.04332465,  0.04503853, ...,  0.03424528,
          0.03795749, -0.00815637],
        [ 0.01519317,  0.03415668,  0.02380535, ..., -0.01916664,
         -0.03218891, -0.02113454],
        ...,
        [ 0.01234799,  0.03600794, -0.01888558, ...,  0.01676476,
          0.01315702, -0.0133096 ],
        [-0.00578463,  0.04745293,  0.01426345, ..., -0.04883779,
         -0.01087344,  0.01100942],
        [ 0.03822645, -0.0235841 , -0.01976987, ..., -0.03409418,
          0.04030878, -0.0056543 ]]], dtype=float32)>

In [34]:
# Model 0: Getting a baseline - Naive Bayes
train_labels = train_labels.astype('int') # sklearn cannot recognize object type
val_labels = val_labels.astype('int')

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()), # convert words to numbers using tfidf
                    ("clf", MultinomialNB()) # model the text
])

# Fit the pipeline to the training data
model_0.fit(train_text, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [27]:
baseline_score = model_0.score(val_text, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%")

Our baseline model achieves an accuracy of: 67.77%


In [28]:
# Make predictions
baseline_preds = model_0.predict(val_text)
baseline_preds[:20]

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [29]:
baseline_preds = list(map(lambda x: "YES" if x == 1 else "NO", baseline_preds))
baseline_preds = np.array(baseline_preds)
val_labels_arr = list(map(lambda x: "YES" if x == 1 else "NO", val_labels))
val_labels_arr = np.array(val_labels_arr)

In [30]:
import pandas as p

preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': baseline_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

In [31]:
val_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': val_labels_arr,
}

val_dict = pd.DataFrame(val_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(val_dict.to_json(orient='records'))

In [32]:
from pyevall.evaluation import PyEvALLEvaluation
from pyevall.utils.utils import PyEvALLUtils
from pyevall.metrics.metricfactory import MetricFactory

test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

2025-03-12 12:59:48,153 - pyevall.evaluation - INFO -             evaluate() - Evaluating the following metrics ['Accuracy', 'FMeasure']
2025-03-12 12:59:48,207 - pyevall.metrics.metrics - INFO -             evaluate() - Executing accuracy evaluation method
2025-03-12 12:59:48,327 - pyevall.metrics.metrics - INFO -             evaluate() - Executing fmeasure evaluation method
{
  "metrics": {
    "Accuracy": {
      "name": "Accuracy",
      "acronym": "Acc",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "average": 0.6776556776556777
        }],
        "average_per_test_case": 0.6776556776556777
      }
    },
    "FMeasure": {
      "name": "F-Measure",
      "acronym": "F1",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "classes": {
            "NO": 0.35294117647058826,
            "YES": 

In [33]:
## Model 1: A simple dense model

In [34]:
!curl -O https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10246  100 10246    0     0  24445      0 --:--:-- --:--:-- --:--:-- 24511


In [35]:
# Import series of helper functions for the notebook
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

In [36]:
# Create tensorboard callback (need to create a new one for each model)
from helper_functions import create_tensorboard_callback

# Create directory to save TensorBoard logs
SAVE_DIR = "model_logs"

In [37]:
# Build model with the Functional API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string") # inputs are 1-dimensional strings
x = text_vectorizer(inputs) # turn the input text into numbers
x = embedding(x) # create an embedding of the numerized numbers
x = layers.GlobalAveragePooling1D()(x) # lower the dimensionality of the embedding (try running the model without this layer and see what happens)
outputs = layers.Dense(1, activation="sigmoid")(x) # create the output layer, want binary outputs so use sigmoid activation
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense") # construct the model

In [38]:
# Compile model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [39]:
# Get a summary of the model
model_1.summary()

Model: "model_1_dense"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 1)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ text_vectorization_1            │ (None, 12)             │             0 │
│ (TextVectorization)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (None, 12, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,280,129 (4.88 MB)

 Trainable params: 1,280,129 (4.88 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# Fit the model
model_1_history = model_1.fit(train_text, # input sentences can be a list of strings due to text preprocessing layer built-in model
                              train_labels,
                              epochs=5,
                              validation_data=(val_text, val_labels),
                              callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR, 
                                                                     experiment_name="simple_dense_model")])

Saving TensorBoard log files to: model_logs/simple_dense_model/20250312-125949
Epoch 1/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.6025 - loss: 0.6866 - val_accuracy: 0.6227 - val_loss: 0.6521
Epoch 2/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.6627 - loss: 0.6366 - val_accuracy: 0.6484 - val_loss: 0.6191
Epoch 3/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.7977 - loss: 0.5545 - val_accuracy: 0.6813 - val_loss: 0.5911
Epoch 4/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.8820 - loss: 0.4515 - val_accuracy: 0.6850 - val_loss: 0.5711
Epoch 5/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9175 - loss: 0.3555 - val_accuracy: 0.6703 - val_loss: 0.5682


In [41]:
# Check the results
model_1.evaluate(val_text, val_labels)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6402 - loss: 0.5865 


[0.5681727528572083, 0.6703296899795532]

In [42]:
embedding.weights

[<Variable path=embedding_1/embeddings, shape=(10000, 128), dtype=float32, value=[[ 1.6185628e-02 -2.2908606e-02  3.6713365e-03 ...  1.0644381e-03
   -1.3320196e-02  1.1132012e-02]
  [-3.0561913e-02  9.7275115e-05  3.7245136e-02 ... -3.5818513e-02
    1.1685763e-02  2.1794882e-02]
  [-2.2927000e-01  2.4043995e-01  2.0938027e-01 ...  1.7290576e-01
   -1.3500549e-01 -2.5007173e-01]
  ...
  [ 4.3939881e-02 -1.8383670e-03 -1.3910697e-02 ... -7.0212550e-02
   -6.9308013e-04  2.6999012e-02]
  [-8.2310095e-02  8.6275056e-02  7.5602859e-02 ...  3.2269169e-02
   -7.5236022e-02  5.3158468e-03]
  [-2.6909575e-02  1.9897748e-02  2.8800208e-02 ...  3.4669239e-02
   -4.4175364e-02 -4.7479294e-02]]>]

In [43]:
embed_weights = model_1.get_layer("embedding_1").get_weights()[0]
print(embed_weights.shape)

(10000, 128)


In [44]:
# Make predictions (these come back in the form of probabilities)
model_1_pred_probs = model_1.predict(val_text)
model_1_pred_probs[:10] # only print out the first 10 prediction probabilities

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[0.29353544],
       [0.8356519 ],
       [0.6173441 ],
       [0.297513  ],
       [0.8190701 ],
       [0.72418046],
       [0.7883606 ],
       [0.18447676],
       [0.80735606],
       [0.32034737]], dtype=float32)

In [45]:
# Turn prediction probabilities into single-dimension tensor of floats
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs)) # squeeze removes single dimensions
model_1_preds = np.array(model_1_preds)
model_1_preds = model_1_preds.astype('int') 
model_1_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1])

In [46]:
model_1_preds = list(map(lambda x: "YES" if x == 1 else "NO", model_1_preds))
model_1_preds = np.array(model_1_preds)
model_1_preds

array(['NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO', 'YES', 'NO',
       'NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES',
       'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO',
       'YES', 'YES', 'NO', 'NO', 'NO', 'YES', 'NO', 'YES', 'YES', 'NO',
       'YES', 'YES', 'NO', 'YES', 'NO', 'NO', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'YES',
       'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'NO',
       'YES', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'YES',
       'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'YES', 'YES', 'YES',
       'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'YES',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES',
       'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'YES'

In [47]:
preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': model_1_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions_model2.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

In [48]:
test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions_model2.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

2025-03-12 13:00:02,129 - pyevall.evaluation - INFO -             evaluate() - Evaluating the following metrics ['Accuracy', 'FMeasure']
2025-03-12 13:00:02,185 - pyevall.metrics.metrics - INFO -             evaluate() - Executing accuracy evaluation method
2025-03-12 13:00:02,312 - pyevall.metrics.metrics - INFO -             evaluate() - Executing fmeasure evaluation method
{
  "metrics": {
    "Accuracy": {
      "name": "Accuracy",
      "acronym": "Acc",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "average": 0.6703296703296703
        }],
        "average_per_test_case": 0.6703296703296703
      }
    },
    "FMeasure": {
      "name": "F-Measure",
      "acronym": "F1",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "classes": {
            "NO": 0.5544554455445544,
            "YES": 0

In [49]:
## Model 2: LSTM

In [50]:
# Set random seed and create embedding layer (new embedding layer for each model)
tf.random.set_seed(42)
from tensorflow.keras import layers
model_2_embedding = layers.Embedding(input_dim=max_vocab_length,
                                     output_dim=128,
                                     embeddings_initializer="uniform",
                                     input_length=max_length,
                                     name="embedding_2")


# Create LSTM model
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_2_embedding(x)
print(x.shape)
# x = layers.LSTM(64, return_sequences=True)(x) # return vector for each word in the Tweet (you can stack RNN cells as long as return_sequences=True)
x = layers.LSTM(64)(x) # return vector for whole sequence
print(x.shape)
# x = layers.Dense(64, activation="relu")(x) # optional dense layer on top of output of LSTM cell
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

(None, 12, 128)
(None, 64)


/Users/naranja/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [51]:
# Compile model
model_2.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [52]:
model_2.summary()

Model: "model_2_LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 1)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ text_vectorization_1            │ (None, 12)             │             0 │
│ (TextVectorization)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_2 (Embedding)         │ (None, 12, 128)        │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,329,473 (5.07 MB)

 Trainable params: 1,329,473 (5.07 MB)

 Non-trainable params: 0 (0.00 B)

In [53]:
# Fit model
model_2_history = model_2.fit(train_text,
                              train_labels,
                              epochs=5,
                              validation_data=(val_text, val_labels),
                              callbacks=[create_tensorboard_callback(SAVE_DIR, 
                                                                     "LSTM")])

Saving TensorBoard log files to: model_logs/LSTM/20250312-130002
Epoch 1/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - accuracy: 0.6029 - loss: 0.6803 - val_accuracy: 0.6374 - val_loss: 0.6043
Epoch 2/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - accuracy: 0.7934 - loss: 0.4615 - val_accuracy: 0.6740 - val_loss: 0.6834
Epoch 3/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.9330 - loss: 0.1770 - val_accuracy: 0.6557 - val_loss: 0.9275
Epoch 4/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - accuracy: 0.9709 - loss: 0.0964 - val_accuracy: 0.6740 - val_loss: 1.2252
Epoch 5/5
77/77 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.9818 - loss: 0.0569 - val_accuracy: 0.6740 - val_loss: 1.3708


In [54]:
# Make predictions on the validation dataset
model_2_pred_probs = model_2.predict(val_text)
model_2_pred_probs.shape, model_2_pred_probs[:10] # view the first 10

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step


((273, 1),
 array([[0.04413156],
        [0.99685997],
        [0.99430186],
        [0.06182545],
        [0.99773085],
        [0.99582183],
        [0.9981026 ],
        [0.07403131],
        [0.99628466],
        [0.00190355]], dtype=float32))

In [55]:
# Round out predictions and reduce to 1-dimensional array
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds = np.array(model_2_preds)
model_2_preds = model_2_preds.astype('int') 

model_2_preds = list(map(lambda x: "YES" if x == 1 else "NO", model_2_preds))
model_2_preds = np.array(model_2_preds)

In [56]:
preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': model_2_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions_model3.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

In [57]:
test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/predictions_model3.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

2025-03-12 13:00:19,257 - pyevall.evaluation - INFO -             evaluate() - Evaluating the following metrics ['Accuracy', 'FMeasure']
2025-03-12 13:00:19,309 - pyevall.metrics.metrics - INFO -             evaluate() - Executing accuracy evaluation method
2025-03-12 13:00:19,467 - pyevall.metrics.metrics - INFO -             evaluate() - Executing fmeasure evaluation method
{
  "metrics": {
    "Accuracy": {
      "name": "Accuracy",
      "acronym": "Acc",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "average": 0.673992673992674
        }],
        "average_per_test_case": 0.673992673992674
      }
    },
    "FMeasure": {
      "name": "F-Measure",
      "acronym": "F1",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "classes": {
            "NO": 0.47953216374269003,
            "YES": 0.

In [59]:
# Make predictions on the test dataset
model_0_test_probs = model_0.predict(test_df["text"].to_numpy())
model_0_test_probs.shape, model_0_test_probs

((697,),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 

In [60]:
# Make predictions on the test dataset
model_1_test_probs = model_1.predict(test_df["text"].to_numpy())
model_1_test_probs.shape, model_1_test_probs

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step


((697, 1),
 array([[0.70772576],
        [0.85915303],
        [0.71925586],
        [0.8027231 ],
        [0.6338783 ],
        [0.8712143 ],
        [0.40695804],
        [0.71341974],
        [0.6544515 ],
        [0.44002563],
        [0.49259475],
        [0.6354533 ],
        [0.5166562 ],
        [0.58426857],
        [0.7051538 ],
        [0.52599394],
        [0.42316854],
        [0.40324402],
        [0.7837341 ],
        [0.80694115],
        [0.94843435],
        [0.93311304],
        [0.6500037 ],
        [0.44949713],
        [0.369227  ],
        [0.53755283],
        [0.89303094],
        [0.598594  ],
        [0.7605082 ],
        [0.84978956],
        [0.4375413 ],
        [0.7717554 ],
        [0.28070086],
        [0.59794635],
        [0.6289771 ],
        [0.6099459 ],
        [0.4371568 ],
        [0.70076156],
        [0.973711  ],
        [0.9259884 ],
        [0.6789039 ],
        [0.4243232 ],
        [0.59128   ],
        [0.40473425],
        [0.7934317 ],

In [61]:
# Make predictions on the test dataset
model_2_test_probs = model_2.predict(test_df["text"].to_numpy())
model_2_test_probs.shape, model_2_test_probs

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


((697, 1),
 array([[9.30774033e-01],
        [9.95218873e-01],
        [9.93754029e-01],
        [9.54145670e-01],
        [9.96509433e-01],
        [9.97442544e-01],
        [7.95901716e-01],
        [9.94386792e-01],
        [9.85825300e-01],
        [1.00478716e-02],
        [9.92337525e-01],
        [9.96764660e-01],
        [9.76935983e-01],
        [9.96649981e-01],
        [9.83946621e-01],
        [7.33264983e-01],
        [9.87981856e-01],
        [9.73628461e-01],
        [9.97580469e-01],
        [9.95125294e-01],
        [9.97243285e-01],
        [9.75247204e-01],
        [9.87826765e-01],
        [2.08733588e-01],
        [5.99787354e-01],
        [5.64197719e-01],
        [9.97431934e-01],
        [5.75640857e-01],
        [9.94829118e-01],
        [9.94866490e-01],
        [1.22780576e-02],
        [9.97479320e-01],
        [4.06558998e-03],
        [9.92094278e-01],
        [9.97353673e-01],
        [9.95078564e-01],
        [9.89028573e-01],
        [8.92400622e-01],
 

In [5]:
## ------------------------------------------------------- blip_caption -----------------------------------------------------------------##

In [6]:
## ------------------------------------------------------- blip_caption -----------------------------------------------------------------##

In [7]:
## ------------------------------------------------------- blip_caption -----------------------------------------------------------------##

In [26]:
train_merged = np.concatenate((train_text, blip_caption_text))

In [27]:
label_merged = np.concatenate((train_labels, blip_caption_labels))

In [41]:
label_merged = label_merged.astype('int') # sklearn cannot recognize object type
val_labels = val_labels.astype('int')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()), # convert words to numbers using tfidf
                    ("clf", MultinomialNB()) # model the text
])

# Fit the pipeline to the training data
model_0.fit(train_merged, label_merged)

baseline_score = model_0.score(val_text, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%\n\n\n")

# Make predictions
baseline_preds = model_0.predict(val_text)
print(baseline_preds[:20])

baseline_preds = list(map(lambda x: "YES" if x == 1 else "NO", baseline_preds))
baseline_preds = np.array(baseline_preds)
val_labels_arr = list(map(lambda x: "YES" if x == 1 else "NO", val_labels))
val_labels_arr = np.array(val_labels_arr)

import pandas as p

preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': baseline_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

val_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': val_labels_arr,
}

val_dict = pd.DataFrame(val_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(val_dict.to_json(orient='records'))

from pyevall.evaluation import PyEvALLEvaluation
from pyevall.utils.utils import PyEvALLUtils
from pyevall.metrics.metricfactory import MetricFactory

test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

Our baseline model achieves an accuracy of: 68.50%



[0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1]
2025-03-13 12:12:49,241 - pyevall.evaluation - INFO -             evaluate() - Evaluating the following metrics ['Accuracy', 'FMeasure']
2025-03-13 12:12:49,349 - pyevall.metrics.metrics - INFO -             evaluate() - Executing accuracy evaluation method
2025-03-13 12:12:49,499 - pyevall.metrics.metrics - INFO -             evaluate() - Executing fmeasure evaluation method
{
  "metrics": {
    "Accuracy": {
      "name": "Accuracy",
      "acronym": "Acc",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": "EXIST2025",
          "average": 0.684981684981685
        }],
        "average_per_test_case": 0.684981684981685
      }
    },
    "FMeasure": {
      "name": "F-Measure",
      "acronym": "F1",
      "description": "Coming soon!",
      "status": "OK",
      "results": {
        "test_cases": [{
          "name": 

In [28]:
from pyevall.evaluation import PyEvALLEvaluation
from pyevall.utils.utils import PyEvALLUtils
from pyevall.metrics.metricfactory import MetricFactory

# Import series of helper functions for the notebook
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

# Create tensorboard callback (need to create a new one for each model)
from helper_functions import create_tensorboard_callback

# Create directory to save TensorBoard logs
SAVE_DIR = "model_logs"

label_merged = label_merged.astype('int') # sklearn cannot recognize object type
val_labels = val_labels.astype('int')

# Build model with the Functional API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string") # inputs are 1-dimensional strings
x = text_vectorizer(inputs) # turn the input text into numbers
x = embedding(x) # create an embedding of the numerized numbers
x = layers.GlobalAveragePooling1D()(x) # lower the dimensionality of the embedding (try running the model without this layer and see what happens)
outputs = layers.Dense(1, activation="sigmoid")(x) # create the output layer, want binary outputs so use sigmoid activation
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense") # construct the model

# Compile model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Fit the model
model_1_history = model_1.fit(train_merged, # input sentences can be a list of strings due to text preprocessing layer built-in model
                              label_merged,
                              epochs=5,
                              validation_data=(val_text, val_labels),
                              callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR, 
                                                                     experiment_name="simple_dense_model")])

# Check the results
model_1.evaluate(val_text, val_labels)

# Make predictions (these come back in the form of probabilities)
model_1_pred_probs = model_1.predict(val_text)
print(model_1_pred_probs[:10]) # only print out the first 10 prediction probabilities

# Turn prediction probabilities into single-dimension tensor of floats
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs)) # squeeze removes single dimensions
model_1_preds = np.array(model_1_preds)
model_1_preds = model_1_preds.astype('int') 

model_1_preds = list(map(lambda x: "YES" if x == 1 else "NO", model_1_preds))
model_1_preds = np.array(model_1_preds)
val_labels_arr = list(map(lambda x: "YES" if x == 1 else "NO", val_labels))
val_labels_arr = np.array(val_labels_arr)

preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': model_1_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions_model2.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

val_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': val_labels_arr,
}

val_dict = pd.DataFrame(val_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(val_dict.to_json(orient='records'))

test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions_model2.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

Saving TensorBoard log files to: model_logs/simple_dense_model/20250313-123508
Epoch 1/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.2759 - loss: -726280.3125 - val_accuracy: 0.6190 - val_loss: 8.9508
Epoch 2/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.2922 - loss: -8951221.0000 - val_accuracy: 0.6154 - val_loss: 35.3519
Epoch 3/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.2942 - loss: -28461606.0000 - val_accuracy: 0.6117 - val_loss: 79.4692
Epoch 4/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.2940 - loss: -59064032.0000 - val_accuracy: 0.6117 - val_loss: 140.3765
Epoch 5/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.2949 - loss: -100150816.0000 - val_accuracy: 0.6117 - val_loss: 217.1088
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6283 - loss: 216.9367
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
2025-03-13 12:35:26,851 - pyevall.evaluation - INFO -           

In [28]:
from pyevall.evaluation import PyEvALLEvaluation
from pyevall.utils.utils import PyEvALLUtils
from pyevall.metrics.metricfactory import MetricFactory

# Import series of helper functions for the notebook
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

# Create tensorboard callback (need to create a new one for each model)
from helper_functions import create_tensorboard_callback

# Create directory to save TensorBoard logs
SAVE_DIR = "model_logs"

label_merged = label_merged.astype('int') # sklearn cannot recognize object type
val_labels = val_labels.astype('int')

tf.random.set_seed(42)
from tensorflow.keras import layers
model_2_embedding = layers.Embedding(input_dim=max_vocab_length,
                                     output_dim=128,
                                     embeddings_initializer="uniform",
                                     input_length=max_length,
                                     name="embedding_2")


# Create LSTM model
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_2_embedding(x)
print(x.shape)
# x = layers.LSTM(64, return_sequences=True)(x) # return vector for each word in the Tweet (you can stack RNN cells as long as return_sequences=True)
x = layers.LSTM(64)(x) # return vector for whole sequence
print(x.shape)
# x = layers.Dense(64, activation="relu")(x) # optional dense layer on top of output of LSTM cell
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

# Compile model
model_2.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Fit model
model_2_history = model_2.fit(train_merged,
                              label_merged,
                              epochs=5,
                              validation_data=(val_text, val_labels),
                              callbacks=[create_tensorboard_callback(SAVE_DIR, 
                                                                     "LSTM")])

# Make predictions on the validation dataset
model_2_pred_probs = model_2.predict(val_text)

# Round out predictions and reduce to 1-dimensional array
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds = np.array(model_2_preds)
model_2_preds = model_2_preds.astype('int') 

model_2_preds = list(map(lambda x: "YES" if x == 1 else "NO", model_2_preds))
model_2_preds = np.array(model_2_preds)
val_labels_arr = list(map(lambda x: "YES" if x == 1 else "NO", val_labels))
val_labels_arr = np.array(val_labels_arr)

preds_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': model_2_preds,
}

preds_dict = pd.DataFrame(preds_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions_model3.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(preds_dict.to_json(orient='records'))

val_dict = {
    'test_case': ['EXIST2025']*len(val_text),
    'id': val_id,
    'value': val_labels_arr,
}

val_dict = pd.DataFrame(val_dict)
output_path = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
with open(output_path, 'w', encoding='utf-8') as output_file:
       output_file.write(val_dict.to_json(orient='records'))

test = PyEvALLEvaluation()
preds = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/blip_predictions_model3.json'
labels = '/Users/naranja/Downloads/NLP Course/lab2_materials/dataset_task4_exist2025/goldgroundtruth.json'
metrics = [
    MetricFactory.Accuracy.value,
    MetricFactory.FMeasure.value,
]
params= dict()
report = test.evaluate(preds, labels, metrics, **params) 
report.print_report()

(None, 12, 128)
(None, 64)
Saving TensorBoard log files to: model_logs/LSTM/20250313-124232
Epoch 1/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 13s 56ms/step - accuracy: 0.2734 - loss: -650777.5000 - val_accuracy: 0.6190 - val_loss: 7.3327
Epoch 2/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.2890 - loss: -1897491.0000 - val_accuracy: 0.6117 - val_loss: 11.4401
Epoch 3/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - accuracy: 0.3045 - loss: -2831091.2500 - val_accuracy: 0.6117 - val_loss: 15.5182
Epoch 4/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - accuracy: 0.3066 - loss: -3743139.7500 - val_accuracy: 0.6154 - val_loss: 19.4832
Epoch 5/5
162/162 ━━━━━━━━━━━━━━━━━━━━ 7s 46ms/step - accuracy: 0.3078 - loss: -4646314.5000 - val_accuracy: 0.6154 - val_loss: 23.3907
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step
2025-03-13 12:43:11,541 - pyevall.evaluation - INFO -             evaluate() - Evaluating the following metrics ['Accuracy', 'FMeasure']
2025-03-13 12:43:11,637 - pyevall.metrics.metrics - IN

In [30]:
test_text = test_df["text"].to_numpy()

In [32]:
label_merged = label_merged.astype('int') # sklearn cannot recognize object type
val_labels = val_labels.astype('int')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()), # convert words to numbers using tfidf
                    ("clf", MultinomialNB()) # model the text
])

# Fit the pipeline to the training data
model_0.fit(train_merged, label_merged)

baseline_score = model_0.score(val_text, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%\n\n\n")

# Make predictions
baseline_preds = model_0.predict(test_text)
baseline_preds

Our baseline model achieves an accuracy of: 68.50%





array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,